.PHONY: clean All

All:
	@echo "----------Building project:[ hangman - Debug ]----------"
	@cd "hangman" && "$(MAKE)" -f  "hangman.mk"
clean:
	@echo "----------Cleaning project:[ hangman - Debug ]----------"
	@cd "hangman" && "$(MAKE)" -f  "hangman.mk" clean
